### PR TITLE
fixed method 61 checksum comparison

### LINKED ISSUE #12: Method 61 checksum comparison flawed
## Expected Behavior
Method 61 should use single digit to compare against checksum single digit.

## Actual Behavior
Method 61 uses double digits for comparison in case of difference of 10.

## Steps to Reproduce the Problem

1. isValidIBAN('DE20280200501234551080')

## Specifications

- Version: 1.2200.0
- Platform: irrelevant

### PR DESCRIPTION
**Pull request by ChrisScheffler**
Fixes #12 

- fixed checksum comparison
- added test

### CODE REVIEW

**Comment by ChrisScheffler** [comment]
This behavior is not defined in the specification, but since the checksum field is 1 digit this change is needed for when the calculated difference is exactly 10.

We could also use the new `moduloDifference` implementation introduced by #5 for
https://github.com/baumerdev/ibantools-germany/blob/58d4195c04bfc8d98c0b698bb0bbc974a7be0924/src/lib/methods/method61.ts#L45
since it does the exact same thing, but your code is more explicit to compare against the spec.

**Comment by baumerdev** [comment]
I'm not entirely sure if this is the right way. I understand your point and if the sum is a multiple of 10 the checksum will be 10 and a double digit number can never equal a single digit number. But...

Some methods like 00 explicitly state what happens if you get something like 10: 
> Ergibt sich nach der Subtraktion der Rest 10, ist die Prüfziffer 0

Other methods like 02 state that calculated double digits check sums are invalid:
>  Ergibt sich als Rest 1, ist die Prüfziffer zweistellig und kann nicht verwendet werden. Die Kontonummer ist dann nicht verwendbar.

And here we have some kind of definition void for that case. Either the check digits for that account number cannot be calculated or someone just forgot to mention that case. I think both are equally likely (especially since some of the method descriptions are extremely badly written)

**Comment by ChrisScheffler** [comment]
> And here we have some kind of definition void for that case. Either the check digits for that account number cannot be calculated or someone just forgot to mention that case.

I think the latter is the case as we have some IBANs (verified by owner) with method 61 which fail this check right now without the change. Furthermore the changed behavior seems to agree with implementations from other IBAN verification services.

> (especially since some of the method descriptions are extremely badly written)

true, true...

**Comment by baumerdev** [comment]
I just checked it at my bank's website and banking app. They decided to go with single unit/valid as well.

**Comment by ChrisScheffler** [comment]
Thank you for checking up on that 👍

**Pull request merged**
